### ISSUE TITLE
Cache issues on startup

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/webapi#19]
Cache issues on startup are currently being worked around by reloading the cache using:

https://api.ala.org.au/admin/webserviceList/clearCache

Need a more permanent fix to avoid having to call that method when startup fails.

Symptoms in log file are like:

```
2018-03-16 11:05:15,257 ERROR [GrailsExceptionResolver] LazyInitializationException occurred when processing request: [GET] /
failed to lazily initialize a collection of role: au.org.ala.webapi.WebService.params, no session or session was closed. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <cache:block>: Error executing tag <g:render>: failed to lazily initialize a collection of role: au.org.ala.webapi.WebService.params, no session or session was closed
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <cache:block>: Error executing tag <g:render>: failed to lazily initialize a collection of role: au.org.ala.webapi.WebService.params, no session or session was closed
	at gsp_webapi_webserviceListbyCategory_gsp$_run_closure2.doCall(gsp_webapi_webserviceListbyCategory_gsp.groovy:84)
	at gsp_webapi_webserviceListbyCategory_gsp.run(gsp_webapi_webserviceListbyCategory_gsp.groovy:87)
	... 9 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: failed to lazily initialize a collection of role: au.org.ala.webapi.WebService.params, no session or session was closed
	at gsp_webapi_webserviceListbyCategory_gsp$_run_closure2_closure4.doCall(gsp_webapi_webserviceListbyCategory_gsp.groovy:81)
	at grails.plugin.cache.CacheTagLib$_closure1.doCall(CacheTagLib.groovy:53)
	... 11 more
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: au.org.ala.webapi.WebService.params, no session or session was closed
	at gsp_webapi_webserviceList_byGroup_gsp.run(gsp_webapi_webserviceList_byGroup_gsp.groovy:107)
	... 13 more
```

**Comment by mbohun** [comment]
@ansell would it be possible to install/add/modify a standard custom startup script `$CATALINA_HOME/bin/setenv.sh` for the "tomcat on api/logger" that would call the https://api.ala.org.au/admin/webserviceList/clearCache REST point (at least as tmp workaround) ?

REFERENCES:
- https://tomcat.apache.org/tomcat-8.0-doc/RUNNING.txt (search for `setenv.sh`)
